//Initialization of plots
var plotPulp = new String("'Pumpkin' (Tim Roth) and 'Honey Bunny' (Amanda Plummer) are having breakfast in a diner. They decide to rob it after realizing they could make money off the customers as well as the business, as they did during their previous heist. Moments after they initiate the hold-up, the scene breaks off and the title credits roll.");

var plotReservoir = new String("Eight men eat breakfast at a Los Angeles diner before their planned diamond heist. Six of them use aliases: Mr. Blonde (Michael Madsen), Mr. Blue (Eddie Bunker), Mr. Brown (Quentin Tarantino), Mr. Orange (Tim Roth), Mr. Pink (Steve Buscemi), and Mr. White (Harvey Keitel). With them are gangster Joe Cabot (Lawrence Tierney), the organizer of the heist and his son, 'Nice Guy Eddie' (Chris Penn). <br/>After they leave the diner, the action abruptly cuts to a speeding car, in which Mr. White comforts Mr. Orange, who has been shot in the abdomen and is bleeding profusely. Shortly after they reach an abandoned warehouse, Mr. Pink arrives and angrily suggests that the job was a setup due to the rapid police response. Mr. White tells Mr. Pink that Mr. Brown was killed during the heist, and the men discuss Mr. Blonde, who murdered several civilians after the alarm triggered. Mr. White is angered that Joe, an old friend of his, employed such a 'psychopath' and agrees about a possible setup while Mr. Pink reveals that he escaped with the diamonds and hid them in a secure location. They argue over whether to take the now unconscious Mr. Orange to a hospital. Mr. White also reveals that he has told Mr. Orange his name and home town. [...]");

var plotTitanic = new String("In 1996, treasure hunter Brock Lovett and his team aboard the research vessel Keldysh search the wreck of RMS Titanic for a necklace with a rare diamond, the Heart of the Ocean. They recover a safe containing a drawing of a young woman wearing only the necklace. The drawing is dated April 14, 1912, the day Titanic struck the iceberg. Rose Dawson Calvert claims to be the person in the drawing, visits Lovett and tells of her experiences aboard Titanic.");

var plotRounders = new String("Gifted poker player Mike McDermott (Matt Damon) loses his entire $30,000 bankroll in a hand of Texas hold'em against Teddy 'KGB' (John Malkovich), a Russian mobster who runs an illegal underground poker room. Shaken, Mike decides to concentrate on law school, while promising his girlfriend and fellow law student Jo (Gretchen Mol) that he will not play poker anymore. Mentor and fellow rounder Knish (John Turturro) offers him a part-time job driving a delivery truck to make ends meet.");

var plotSaw6 = new String("Simone (Tanedra Howard) and Eddie (Marty Moreau), two predatory lenders, awaken wearing head harnesses with screws poised to pierce their temples. A videotape informs them that the one who sets more flesh weight on their tray of the caged-in scale will survive: Eddie cuts fat from his torso, but Simone chops off her left arm, leaving Eddie to be killed by the screws. Detective Mark Hoffman (Costas Mandylor) is called to the scene by FBI Agent Dan Erickson (Mark Rolston), who found Peter Strahm's fingerprints around the room. Erickson reveals that Lindsey Perez (Athena Karkanis) is still alive: because the identity of Jigsaw's second accomplice was still unknown, Erickson had her survival kept secret to protect her.");

var plotDiner = new String("Pierre Brochant, a Parisian publisher, attends a weekly 'idiots' dinner, where guests, who are prominent Parisian businessmen, must bring along an 'idiot' who the other guests can ridicule. At the end of the dinner, the evening's champion idiot is selected. <br/> With the help of an 'idiot scout', Brochant manages to find a 'gem', François Pignon, a Finance Ministry employee whose passion is building replicas of landmarks with matchsticks. When Brochant starts to suffer from bad back, his wife, Christine, leaves him shortly before Pignon arrives at his apartment. Brochant initially wants Pignon to leave, but instead becomes reliant on him, because of his back problem, and his need to resolve his relationship problems. He solicits Pignon's assistance in making a series of telephone calls to locate his wife, but Pignon gaffes each time, including revealing the existence of Brochant's mistress, Marlene Sasseur, to his wife, Christine.");

var plotEmmanuelle = new String("Emmanuelle (Sylvia Kristel) flies to Bangkok to meet her husband Jean (Daniel Sarky), a diplomat, who asks her if she had any other lovers while she was in Paris; she replies that she has not. After taking a nude swim, Emmanuelle is approached by a pretty young girl named Marie-Ange (Christine Boisson), who asks to meet Emmanuelle at her house. Marie-Ange arrives at the house and finds Emmanuelle sleeping, and takes advantage of the situation to feel her body. Emmanuelle wakes up and they go outside where Marie-Ange asks Emmanuelle if she has any photos of herself and Jean having sex, after Emmanuelle replies she does not, Marie-Ange takes a French magazine with a photo of actor Paul Newman and begins to masturbate in front of Emmanuelle. Emmanuelle confesses to Marie-Ange that while she did not cheat on her husband in Paris, she did have sex with two strangers on the flight over to Bangkok. Emmanuelle begins to masturbate as she recounts the tryst. At night, Emmanuelle tells Jean about Marie-Ange's younger girl's lack of shame, which leads to Jean encourages her to pursue the friendship.");

var plotFight = new String("The unnamed narrator is a travelling automobile company employee who suffers from insomnia. His doctor refuses to give him medication and advises him to visit a support group to witness more severe suffering. The narrator attends a support group for testicular cancer victims and, after fooling them into thinking that he is a fellow victim, finds an emotional release that relieves his insomnia. He becomes addicted to attending support groups and pretending to be a victim, but the presence of another impostor, Marla Singer, disturbs him, so he negotiates with her to avoid their meeting at the same groups.");
